# Production environment
version: "3"

services:
  proxy:
    restart: always
    build: ./proxy
    volumes:
      - static-data:/app/staticfiles
    ports:
      - "80:80"

  app:
    restart: always
    build: ./app
    volumes:
      - static-data:/app/staticfiles
    environment:
      RUNENV: "PRODUCTION"
    command: bash cmd.production.sh

  postgres:
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:3.2
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  static-data:
    driver: local
