# Development environment
version: "3"

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      RUNENV: "DEV via docker-compose"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
