# Production environment
version: '2'

services:
  proxy:
    restart: always
    build: ./proxy
    links:
      - app
    volumes:
      - static-data:/app/staticfiles
    ports:
      - "80:80"

  app:
    restart: always
    build: ./app
    links:
      - postgres
      - redis
    volumes:
      - static-data:/app/staticfiles
    expose:
      - "9000"
    environment:
      RUNENV: "PRODUCTION"
    command: bash cmd.production.sh

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  static-data:
    driver: local
