# Development environment
version: '2'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    volumes:
      - ./web:/app
    environment:
      NAME: "Django running under docker-compose!"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
