# Production environment
version: '2'

services:
  proxy:
    restart: always
    image: nginx:stable
    links:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static-data:/app/staticfiles
    ports:
      - "9005:80"

  web:
    restart: always
    build: ./web
    links:
      - postgres
      - redis
    volumes:
      - static-data:/app/staticfiles
    expose:
      - "9001"
    environment:
      NAME: "Django in PRODUCTION"
    command: bash cmd.production.sh

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  static-data:
    driver: local
